INSERT INTO P_FAVOR_MUSIC VALUES(1,1);
INSERT INTO P_FAVOR_MUSIC VALUES(1,2);
INSERT INTO P_FAVOR_MUSIC VALUES(1,3);
INSERT INTO P_FAVOR_MUSIC VALUES(2,2);
INSERT INTO P_FAVOR_MUSIC VALUES(2,3);
SELECT * FROM P_FAVOR_MUSIC pfm ;
SELECT * FROM P_USER pu ;
SELECT * FROM P_MUSIC pm ;

SELECT * FROM P_PLAYLOG pp ;

DROP TABLE P_LIST_MUSIC;

CREATE TABLE P_LIST_MUSIC (
   listadd_no NUMBER,
   mylist_no NUMBER CONSTRAINT p_list_music_mylist_no_fk REFERENCES P_MYLIST(mylist_no) ON DELETE CASCADE,
   m_no NUMBER CONSTRAINT p_list_music_m_no_fk REFERENCES P_MUSIC(m_no) ON DELETE CASCADE
);
CREATE SEQUENCE P_LIST_MUSIC_NO_SEQ
   START WITH 1
   INCREMENT BY 1;

INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,1,1);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,1,2);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,1,3);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,2,2);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,3,3);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,4,4);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,5,1);
INSERT INTO P_LIST_MUSIC VALUES(P_LIST_MUSIC_NO_SEQ.NEXTVAL,5,3);
  